plugin:
  debug: false
  notify_on_kill: false
  notify_on_level: true

database:
  type: SQLite
  port: 3306
  name: petsuite
  user: root
  password: root
  hostname: localhost
  
levels:
  '2': 5
  '3': 25
  '4': 75
  '5': 150
  '6': 200
  '7': 300

skills:
  skins:
    stone_skin: 3
    iron_skin: 5
    diamond_skin: 7
  fangs:
    stone_fang: 2
    iron_fang: 4
    diamond_fang: 6